name: "sast-scan"

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: OWASP dependency check
      run: |
       VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
       wget "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" -O ./dependency-check.zip 
       unzip dependency-check.zip
    - name: run scan with ODC
      run: |
        dependency-check/bin/dependency-check.sh --project "goaccesslambda" --scan . --exclude ./dependency-check/
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sast report
        path: |
          ./dependency-check-report.html
 
